apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sam-web-server.fullname" . }}-data-configmap
  labels:
    {{- include "sam-web-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ range $key, $value := .Values.dataConfig.model }}
    {{ $key | nindent 4 }}:
      {{ print "name: " $value.name | nindent 6 }}
      {{ print "path: " $value.path | nindent 6 }}
    {{ end }}
    {{ range $key, $value := .Values.dataConfig.data }}
    {{ $key | nindent 4 }}:
      {{ print "path: " $value.path | nindent 6 }}
      {{ print "embedding: " $value.embedding | nindent 6 }}
    {{ end }}
